# Generated by Django 4.0 on 2022-01-13 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dateAdmission', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('job', models.CharField(max_length=255)),
                ('unbalancing', models.CharField(max_length=255)),
                ('subject', models.ManyToManyField(to='teachersPage.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255)),
                ('manyVariables', models.IntegerField(default=1)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='TypeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('orderQuestions', models.CharField(max_length=255)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.test')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=255)),
                ('firstname', models.CharField(max_length=255)),
                ('patronymic', models.CharField(blank=True, max_length=255)),
                ('sex', models.BooleanField()),
                ('birthdate', models.DateField()),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('fioGuardian', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('stGroup', models.ManyToManyField(to='teachersPage.StGroup')),
            ],
        ),
        migrations.AddField(
            model_name='stgroup',
            name='teacher',
            field=models.ManyToManyField(to='teachersPage.Teacher'),
        ),
        migrations.AddField(
            model_name='stgroup',
            name='typeGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.typegroup'),
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('description', models.TextField()),
                ('correctAnswer', models.CharField(max_length=255)),
                ('photo', models.ImageField(upload_to='photosQuestions/%Y/%m/%d/')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.test')),
            ],
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=255)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.IntegerField()),
                ('uploadDate', models.DateField()),
                ('studentAnswer', models.TextField()),
                ('score', models.IntegerField()),
                ('photo', models.ImageField(upload_to='photosAnswer/%Y/%m/%d/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.test')),
            ],
        ),
    ]
