# Generated by Django 4.0 on 2022-01-13 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersPage', '0002_alter_student_email_alter_student_fioguardian_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachersPage.modules'),
        ),
    ]
