# Generated by Django 4.0 on 2022-01-13 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachersPage', '0003_test_module'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Modules',
            new_name='Module',
        ),
    ]
