# Generated by Django 3.2.9 on 2022-04-02 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersPage', '0004_rename_modules_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='correctAnswer',
        ),
        migrations.CreateModel(
            name='QuestionVariantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VariantAnswer', models.TextField()),
                ('correctAnswer', models.BooleanField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachersPage.question')),
            ],
        ),
    ]
