# Generated by Django 3.2.9 on 2022-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersPage', '0005_auto_20220402_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(null=True, upload_to='photosQuestions/%Y/%m/%d/'),
        ),
    ]
