# Generated by Django 3.2.9 on 2022-04-02 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersPage', '0006_alter_question_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photosQuestions/%Y/%m/%d/'),
        ),
    ]
