# Generated by Django 3.2.9 on 2022-04-16 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachersPage', '0007_alter_question_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkQ', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
