# Generated by Django 3.2.9 on 2022-04-16 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachersPage', '0008_checkquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='checkQ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teachersPage.checkquestion'),
        ),
    ]
